### ISSUE TITLE
Ionic 1.2

### ISSUE THREAD

**Issue by Manduro** [twinssbc/Ionic-Calendar#10]
Ionic 1.2 was released in the past week, with many changes and a new slide box component (as quoted below). I will probably check compatibility in a week or two and will try to integrate the new component as well.

> ### New Slide Box
> One of the most requested improvements in Ionic was a better Slide Box component for UIs that let the user swipe between a set of slides.
> 
> Today, we are releasing a new Slide Box based on the amazing Swiper widget. This is, by far, the most > feature rich and widely used slider component out there, and it’s no surprise that many Ionic users > requested us to support it officially. It also happens to be the new slider and markup that Ionic 2 uses, so you’ll be future proof!
> 
> With 1.2, we still support the old slider, but it’s deprecated and will be removed in a future release.
> 
> To use the new slider, use the `<ion-slides>` tag:
> ```html
<ion-slides options="options" slider="slider">
  <ion-slide-page>
  </ion-slide-page>
</ion-slides>
```
> The options argument is passed directly to Swiper and follows the official API options. Set a `$scope.$watch` on slider to get full access to the Swiper object to control the internal API.

**Comment by twinssbc** [comment]
cool, I will also have a look.

**Comment by Manduro** [comment]
It seems to work fine here! The slide box feels a lot faster even without using the new slider box in the template. Still have to try that.

**Comment by Manduro** [comment]
Ionic 1.2 works fine with the old slide box, and it will be deprecated in 1.3, which will probably take a while. Let's leave it as is for now.
