### ISSUE TITLE
Adding events one by one and not losing them in process

### ISSUE THREAD

**Issue by TheMeteoRain** [twinssbc/Ionic-Calendar#100]
Hello,

Using your calendar as one of my school project's backbone. I've been changing the source code somewhat. Though I can't seem to find the place where I can modify it so that
A. I can add an event
B. Add another event without losing the last one
C. Keep doing that 

I'm not using backend techniques, just plain local storaging.
Also I scrapped the randomEvent function. Made it so it only passes one at a time with customized fields.

Thanks in advance :)

**Comment by twinssbc** [comment]
@TheMeteoRain You need to add a new event in a separate page. 
Normally what you can do is:
1. Put a button somewhere which can navigate to a new page
2. Add the navigation logic in the timeSelected callback exposed by the calendar
Once you successfully added the event, you can navigate back to the calendar page and passes the events stored in local storage.

**Comment by TheMeteoRain** [comment]
@twinssbc 
Maybe I should have added more info. I have all the things mentioned.
I can access the selected date/data (that data comes from timeSelected, like you told) in calendar view and also I have a button to add event(not events).

Problem is whenever I add new event it replaces the old one, so I can never have multiple events.
I just need guidance where to fork the code, so it does not scrap past events.
Because it can get pretty messy there, since there is not documentation right in the source code.

Thanks

**Comment by twinssbc** [comment]
@TheMeteoRain 
I think your current approach is correct.
The calendar watches the eventSource array, whenever it's changed, it will refresh the view.

I don't quite understand what you mean by the new events replaces the old one.
When you add a new event, I suppose you add one more entry in local storage. And next time you fetch events from the local storage, there will be two entries and they both get passed to eventSource array?

**Comment by TheMeteoRain** [comment]
@twinssbc 
The same thing happens when you at your own createRandomEvents() function.
It will create events and shows them, but after you click it again, all the previous ones go away and are replaced with new ones. Hope that clears it up of what is happening.

But yeah. I think I got it now. Made my own events array. Seems to be working just fine with this.

**Comment by twinssbc** [comment]
So the events being displayed are the ones in the events array. As long as the new event doesn't replace the existing event in the array, you should be able to see both the existing one and the new one.
