### ISSUE TITLE
Adding an 'AM' or 'PM' to event detail 

### ISSUE THREAD

**Issue by aupadhyay** [twinssbc/Ionic-Calendar#103]
Hi! 
I've been trying to figure out how to add the 'AM'/'PM' text to the end of my event detail in the month view. I've attached a picture of what I have so far.  [http://imgur.com/a/1SVMQ](http://imgur.com/a/1SVMQ)

How can I add the PM after both times?

**Comment by twinssbc** [comment]
U can provide your own custom view template, check monthviewEventDetailTemplateUrl option in README

**Comment by aupadhyay** [comment]
Awesome I was able to figure it out using this code for my monthViewEventDetailTemplate: 
```
<td ng-if="!event.allDay" class="monthview-eventdetail-timecolumn">
    {{::event.startTime.getHours() < 12 ? event.startTime.getHours() + ':' + event.startTime.getMinutes() + 'am' :  (event.startTime.getHours()-12) + ':' + event.startTime.getMinutes() +  'pm'}}
    -
    {{::event.endTime.getHours() < 12 ? event.endTime.getHours() + ':' + event.endTime.getMinutes() + 'am' : (event.endTime.getHours() - 12) + ':' + (event.endTime.getMinutes()) + 'pm'}}
</td>
```

Thanks!
