### ISSUE TITLE
Time Format For Event

### ISSUE THREAD

**Issue by yorki404** [twinssbc/Ionic-Calendar#104]
Hello Everyone

I have a time format like this in my database : Mon Nov 28 2016 00:00:00 GMT 0200 (Egypt Standard Time)

How can i build an event using this format ?

**Comment by twinssbc** [comment]
@yorki404, the startTime and endTime field in the event is the Date type. So you need to parse your datetime string fetched from your database into a valid string.
JavaScript has Date.parse method which accepts a string representing an RFC2822 or ISO 8601 date.
If your time format is special, you have to use your own way to parse it.

**Comment by yorki404** [comment]
Thank you so much @twinssbc 
I have made a work around using moment.js and slice() javascript method to make the calendar work with my dates.

Thank you again.
