### ISSUE TITLE
Month View event detail display issue

### ISSUE THREAD

**Issue by hussainak** [twinssbc/Ionic-Calendar#105]
Hi @twinssbc 

Please see the attached file. There is a difference in how month view events are displayed on iOS and Android, I have tested this on devices as well. I am using the latest release of ionic-calendar. Have you resolved this one before?

I have also removed my monthview-event-detail-template-url and tested, still the same issue.

Regards
<img width="813" alt="anamoly" src="https://cloud.githubusercontent.com/assets/1008911/20741865/fd107a76-b720-11e6-820c-bcde79416e50.png">

**Comment by twinssbc** [comment]
@hussainak Could you provide the html and css code related to this calendar control?
Is there any other elements after the calendar control in the same page?
Did you apply any css styles to that page?

**Comment by hussainak** [comment]
Calendar HTML

`<ion-view view-title="Planner">
  <ion-nav-buttons side="right">
    <button class="button" ng-disabled="isToday()" ng-click="today()">Today</button>
    <button class="button" ng-click="changeMode('month')">M</button>
    <button class="button" ng-click="changeMode('week')">W</button>
    <button class="button" ng-click="changeMode('day')">D</button>
  </ion-nav-buttons>
  <ion-content scroll="true" class="main-content">

    <div class="item item-divider item-text-wrap">
      <p>{{viewTitle}} {{plannerName}}</p>
    </div>
    <calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource"
              range-changed="reloadSource(startTime, endTime)"
              event-selected="onEventSelected(event)" title-changed="onViewTitleChanged(title)"
              time-selected="onTimeSelected(selectedTime, event)"
              step="15" noEventsLabel="true" showEventDetail="true"
              monthview-event-detail-template-url="monthviewEventDetailTemplateUrl">

    </calendar>
  </ion-content>
</ion-view>`

MonthView html template

`<ion-content class="event-detail-container" has-bouncing="false" ng-show="showEventDetail" overflow-scroll="false">
  <table class="table table-bordered table-striped table-fixed event-detail-table">
    <tr ng-repeat="event in selectedDate.events" ng-click="eventSelected({event:event})">
      <td ng-if="!event.allDay" class="monthview-eventdetail-timecolumn" style="width:90px">{{::event.startTime|date: 'hh:mm a'}}
        -
        {{::event.endTime|date: 'hh:mm a'}}
      </td>
      <td ng-if="event.allDay" class="monthview-eventdetail-timecolumn">All day</td>
      <td class="event-detail item-text-wrap">
        <p><strong>Event:</strong> {{::event.title}}</p>
        <p> <strong>Starts:</strong> {{::event.startTime|date: 'hh:mm a'}} - {{::event.islamic_start_date}}</p>
        <p><strong>Ends:</strong> {{::event.endTime|date: 'hh:mm a'}} - {{::event.islamic_finish_date}}</p>
        <strong ng-if="event.description">Description:</strong>
        <p ng-bind-html="event.description"> </p>
      </td>
    </tr>
    <tr ng-if="!selectedDate.events">
      <td class="no-event-label" ng-bind="::noEventsLabel"></td>
    </tr>
  </table>

</ion-content>`

**Comment by hussainak** [comment]
Hi @twinssbc 
I tried playing around with css in chrome and unable to pinpoint why this is happening for iOS, were you able to look at this?

Regards

**Comment by twinssbc** [comment]
@hussainak If you set scroll="false" in Calendar HTML, will it work?

**Comment by twinssbc** [comment]
Also event-detail-container has the margin-top which is set to be the height of the above calendar.
```
.event-detail-container {
    border-top: 2px darkgrey solid;
    margin-top: 262px;
}
```
The calendar should contain 6 rows, but since you added below element above the calendar, only 5 rows are displayed. So you need to adjust the margin-top of the event-detail-container a bit.

```
    <div class="item item-divider item-text-wrap">
      <p>{{viewTitle}} {{plannerName}}</p>
    </div>
```

**Comment by hussainak** [comment]
Thanks @twinssbc 
scroll = "false" seems to have fixed it but it is unable to override the margin-top css.
![image](https://cloud.githubusercontent.com/assets/1008911/20870529/1f62a23c-bade-11e6-9d1e-5144d52e2da9.png)

**Comment by twinssbc** [comment]
@hussainak you can use !import or specify more specific rule to override css.

**Comment by hussainak** [comment]
Thanks @twinssbc , using !important helped

**Comment by Mohansameer** [comment]
how to add click on event view
