### ISSUE TITLE
How to add the nav bar buttons and month title

### ISSUE THREAD

**Issue by jmblank09** [twinssbc/Ionic-Calendar#115]
I'm in trouble understanding how to use your calendar. How can i add the Month with the buttons just like in your demo?
![image](https://cloud.githubusercontent.com/assets/21171734/22183252/87c89b38-e0f4-11e6-8ce8-73ac3281d3ac.png)

**Comment by twinssbc** [comment]
@jmblank09 
The title and buttons are actually not part of the calendar.
Have a look at the ion-nav-buttons in the ionic documentation.

**Comment by jmblank09** [comment]
Ohh ok. I thought it was part of your template. Thanks!
