### ISSUE TITLE
ionic version

### ISSUE THREAD

**Issue by guironm** [twinssbc/Ionic-Calendar#116]
What ionic version is compatible with this.
I'm stilll a noob i am getting this error:
bower                                 ECONFLICT Unable to find suitable version for ionic

Can you tell me step by step from ionic install to this calendar?
is there a way to install your complete version with angular and ionic via npm or something?

thank you

**Comment by twinssbc** [comment]
@guironm This calendar is compatible with the latest Ionic1 version, 1.3.2. If you want to use Ionic2, you can use the  Ionic2-Calendar.
This calendar is published in bower, so you just need to use below command to install the calendar. The depending Angular and Ionic will be installed automatically.

```
bower install ionic-calendar
```

**Comment by lukeschuyler** [comment]
Can you adjust your bower.json to be `^1.1.1` then?

**Comment by twinssbc** [comment]
@lukeschuyler I have adjusted the ionic version.
