### ISSUE TITLE
showWeeks option

### ISSUE THREAD

**Issue by cornstar94** [twinssbc/Ionic-Calendar#12]
Hi, I couldn't find the showWeeks option in the calendar-tpls.js file. I wonder if it is still going to be implemented as per the README? thanks.

**Comment by twinssbc** [comment]
@cornstar94 I removed this option from the pure AngularJS version, the reason is just because I don't want to add extra column in a mobile device.

Feel free to add it according to the pure AngularJS version. If you have any question, feel free to let me know.
https://github.com/twinssbc/AngularJS-ResponsiveCalendar/blob/master/src/rcalendar/calendar.js

**Comment by cornstar94** [comment]
@twinssbc thanks for the clarification. The ionic calendar is by far the best calendar tool I can find for the ionic framework.  

However, I would like to know how I can change the templates in the library where ionic-calendar is installed? I tried modifying the templates to suit my needs but it doesnt seem to update on localhost. I am relatively new to ionic and angularjs, so any help would be much appreciated. Thanks!

**Comment by twinssbc** [comment]
@cornstar94 Are you referencing calendar-tpls.js or calendar-tpls.min.js? This js file already contains the template code using the templateCache technique. If you take a look at the gruntfile.js, you will see a step called html2js which converts the template html code to the js code.
If you want to modify the template, you need to run *grunt build-tpls* to generate a new version of minimized js file.

**Comment by cornstar94** [comment]
@twinssbc I am referencing to  calendar-tpls.min.js currently. I noticed that I do not have the grunt file in my folders after performing bower install.

I also tried running grunt build-tpls as per your advice but I got the following error:

Fatal error: Unable to find local grunt.
If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project

I tried installing npm at the directory and copied the gruntfile.js in your repo over manually, but it led to an injector module error after i re-run grunt build-tpls. 

What course of action should I take next? Thanks.

**Comment by twinssbc** [comment]
@cornstar94 If you want to modify any code, you should fork it, instead of directly modifying the install version from bower. Then you can generate a new calendar-tpls file and copy it to your current project.

**Comment by cornstar94** [comment]
Ah I see! I'll be sure to try it again.

If you don't mind @twinssbc, could you help me with another minor issue? I am having a little trouble pushing events to my events array in the following code:

    $scope.loadEvents = function () {
            $scope.calendar.eventSource = getEvents();
        };


    function getEvents(object){

            TimeSlotsModel.all()
                .then(function (result) {
                    vm.data = result.data.data;

                    var events = [];

                     angular.forEach(vm.data, function(value,key) {
                 
                        var eventName = value.name;
                        var startDate = new Date(value.startDate);
                        var endDate = new Date(value.endDate);

                        var selectedStartingTime =new Date(value.startTime * 1000 );
                        var selectedEndingTime = new Date(value.endTime * 1000);

                        //timing is not right, needs fixing
                        startTime = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate(),selectedStartingTime.getHours(), selectedStartingTime.getUTCMinutes());
                        endTime = new Date(endDate.getFullYear(), endDate.getMonth(), endDate.getDate(),selectedEndingTime.getUTCHours(), selectedEndingTime.getUTCMinutes());                     
                        // console.log(startTime);
                        events.push({
                            title: 'Event -' + eventName,
                            startTime: startTime,
                            endTime: endTime,
                            allDay: false
                        });


                console.log(value);

                                //value is the object!!
                })
                 return events;

                })
               
             }

Also, my date is correct but timing is off in my printed console. I am using the timepicker from https://github.com/rajeshwarpatlolla/ionic-timepicker. The timepicker code I am using is here : 

    var timePickerCallback =function (val) {
              if (typeof (val) === 'undefined') {
                console.log('Time not selected');
              } else {
                var selectedTime = new Date(val * 1000);
                console.log('Selected epoch is : ', val, 'and the time is ', selectedTime.getUTCHours(), ':', selectedTime.getUTCMinutes(), 'in UTC');
               
               

                $scope.timePickerObject.inputEpochTime = val
              }
            };

      $scope.timePickerObject = {
      inputEpochTime: ((new Date()).getHours() * 60 * 60),  //Optional
      step: 15,  //Optional
      format:12,  //Optional
      titleLabel: '12-hour Format',  //Optional
      setLabel: 'Set',  //Optional
      closeLabel: 'Close',  //Optional
      setButtonType: 'button-positive',  //Optional
      closeButtonType: 'button-stable',  //Optional
      callback: function (val) {    //Mandatory
         vm.newObject.startTime = val; 
         timePickerCallback(val);
      }
    }


Please take a look if you have the time. Thanks :+1:

**Comment by twinssbc** [comment]
@cornstar94 If I understand correct, you have two questions.
1. When you insert a record to the events array, the view doesn't display that new event?
This is by design, check out the Note section in the README, you have to manually trigger the eventSourceChanged event.
2. You got some time difference when using timepicker. Is it because of the timezone?

**Comment by cornstar94** [comment]
@twinssbc As for question 1, I added in the line       
 `$scope.$broadcast('eventSourceChanged',$scope.eventSource);`

and my code is now

      .controller('CalendarCtrl', function ($scope,TimeSlotsModel,$rootScope) {
        var vm = this;


        function goToBackand() {
            window.location = 'http://docs.backand.com';
        }

        function getAll() {
            TimeSlotsModel.all()
                .then(function (result) {
                    vm.data = result.data.data;
                });
        }

        function clearData(){
            vm.data = null;
        }

        function create(object) {
            TimeSlotsModel.create(object)
                .then(function (result) {
                    cancelCreate();
                    getAll();
                });
        }

        function update(object) {
            TimeSlotsModel.update(object.id, object)
                .then(function (result) {
                    cancelEditing();
                    getAll();
                });
        }

        function deleteObject(id) {
            TimeSlotsModel.delete(id)
                .then(function (result) {
                    cancelEditing();
                    getAll();
                });
        }

        function initCreateForm() {
            vm.newObject = {name: '', description: ''};
        }

        function setEdited(object) {
            vm.edited = angular.copy(object);
            vm.isEditing = true;
        }

        function isCurrent(id) {
            return vm.edited !== null && vm.edited.id === id;
        }

        function cancelEditing() {
            vm.edited = null;
            vm.isEditing = false;
        }

        function cancelCreate() {
            initCreateForm();
            vm.isCreating = false;
        }

        // initialising the various methods
        vm.objects = [];
        vm.edited = null;
        vm.isEditing = false;
        vm.isCreating = false;
        vm.getAll = getAll;
        vm.create = create;
        vm.update = update;
        vm.delete = deleteObject;
        vm.setEdited = setEdited;
        vm.isCurrent = isCurrent;
        vm.cancelEditing = cancelEditing;
        vm.cancelCreate = cancelCreate;
        vm.goToBackand = goToBackand;
        vm.isAuthorized = false;
        

        //rootScope refers to the universal scope, .$on is a receiver for the 
        //message 'authorized'
        $rootScope.$on('authorized', function () {
            vm.isAuthorized = true;
            getAll();
        });

        $rootScope.$on('logout', function () {
            clearData();
        });

        if(!vm.isAuthorized){
            $rootScope.$broadcast('logout');
        }

        initCreateForm();
        getAll();

       
        $scope.calendar = {};
        $scope.changeMode = function (mode) {
            $scope.calendar.mode = mode;
        };

        $scope.loadEvents = function () {
            $scope.calendar.eventSource = getEvents();
        };

        $scope.onEventSelected = function (event) {
            console.log('Event selected:' + event.startTime + '-' + event.endTime + ',' + event.title);
        };

        $scope.onViewTitleChanged = function (title) {
            $scope.viewTitle = title;
        };

        $scope.today = function () {
            $scope.calendar.currentDate = new Date();
        };

        $scope.isToday = function () {
            var today = new Date(),
                currentCalendarDate = new Date($scope.calendar.currentDate);

            today.setHours(0, 0, 0, 0);
            currentCalendarDate.setHours(0, 0, 0, 0);
            return today.getTime() === currentCalendarDate.getTime();
        };

        $scope.onTimeSelected = function (selectedTime) {
            console.log('Selected time: ' + selectedTime);
        };
    ///////////////////////////////////////////////////////
        function getEvents(object){

            TimeSlotsModel.all()
                .then(function (result) {
                    vm.data = result.data.data;

                    var events = [];

                     angular.forEach(vm.data, function(value,key) {
                 
                        var eventName = value.name;
                        var startDate = new Date(value.startDate);
                        var endDate = new Date(value.endDate);

                        var selectedStartingTime =new Date(value.startTime * 1000 );
                        var selectedEndingTime = new Date(value.endTime * 1000);

                        //timing is not right, needs fixing
                        startTime = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate(),selectedStartingTime.getHours(), selectedStartingTime.getUTCMinutes());
                        endTime = new Date(endDate.getFullYear(), endDate.getMonth(), endDate.getDate(),selectedEndingTime.getUTCHours(), selectedEndingTime.getUTCMinutes());                     
                        // console.log(startTime);
                        events.push({
                            title: 'Event -' + eventName,
                            startTime: startTime,
                            endTime: endTime,
                            allDay: false
                        });
                //manually triggering eventSourceChanged
                $scope.$broadcast('eventSourceChanged',$scope.eventSource);

                // console.log(events);
                // console.log(value);

                

                
                 //value is the object!!
                })
                 return events;

                })
               
             }`


However, the events are still not rendered here.

**Comment by twinssbc** [comment]
@cornstar94 Now I understand your scenario. Your events array is not bound to the scope, that's why the view doesn't display the events. It's not related to broadcast the change event.
In 
```TimeSlotsModel.all()
            .then(function (result) {
```
Directly assign the events array to $scope.calendar.eventSource.

You can first try some mock data to see if the view can display these events. Next, you can integrate with the backend.

**Comment by cornstar94** [comment]
Thanks @twinssbc,the events are finally rendering! Do you have any suggestions for my 2nd question?

**Comment by twinssbc** [comment]
@cornstar94 It's great that hear that you finally make it work. Are you referring to the timepicker question? I didnt use it before, but i'm happy to help. Do you have any working instance to visit so that I can troubleshoot?

**Comment by cornstar94** [comment]
Hi @twinssbc, thanks for always replying so quickly. I have managed to solve the timepicker issue because I left out a getUTCHours function in my code. 

Thank you very much and I hope you have a great 2016. :)

**Comment by twinssbc** [comment]
@cornstar94 Great, Happy New Year!
