### ISSUE TITLE
I had tried what u had said but i am facing an error by following these link  https://m.youtube.com/watch?v=UVOV2hTkkvE

### ISSUE THREAD

**Issue by gsaikrishna32** [twinssbc/Ionic-Calendar#127]
![capture2](https://cloud.githubusercontent.com/assets/25900718/23152150/f862dcee-f825-11e6-9391-2325b01f628b.PNG)

**Comment by gsaikrishna32** [comment]
sry bro...........i had got the calendar UI.

**Comment by twinssbc** [comment]
Do you still have this issue?

**Comment by twinssbc** [comment]
Solved offline.
