### ISSUE TITLE
The styles are missing

### ISSUE THREAD

**Issue by frank0ch0a** [twinssbc/Ionic-Calendar#129]
I run the app with ionic serve, and the calendar looks well in the explorer, but when I run it in the ios simulator the it lose the styles, attaching image
![simulator screen shot 22 02 2017 9 58 20 a m](https://cloud.githubusercontent.com/assets/2018618/23231743/ea0d449e-f916-11e6-942d-ff3bba6041b2.png)

**Comment by twinssbc** [comment]
@frank0ch0a May I know which version of the calendar and Ionic framework are you using?
Is it working in the real device?

**Comment by frank0ch0a** [comment]
@twinssbc I am using ionic 1 , I fixed the problem changing the order of the url of stylesheets in the index.html file.
