### ISSUE TITLE
Why monthviewEventDetail.html updated.

### ISSUE THREAD

**Issue by akashsky44** [twinssbc/Ionic-Calendar#146]
i updated monthviewEventDetail.html by my own filter u see in below image. but it not show event detail time in 13:29 i want to show this in 1:29. how to do this. many times updated telmplate but any changes not perform.
![delerer](https://user-images.githubusercontent.com/17689498/26880081-ef319fc8-4bb0-11e7-8fdd-d207a9ac19c3.JPG)

**Comment by twinssbc** [comment]
@akashsky44 Actually the template is already bundled into the released js file. So if you directly modify the html file in the templates folder, it doesn't take effect. 
Take a look at monthviewEventDetailTemplateUrl option in README. You need to write your own template file and assign the path to this option.
