### ISSUE TITLE
Month title change not working after date selection

### ISSUE THREAD

**Issue by abouttimeruss** [twinssbc/Ionic-Calendar#152]
In the Month view, after I select a different day, the swipe to the previous or next month looks like it works, but it stays on the same month title. Before you select a different date, you scan swipe and it changes the title as expected. Is this a known issue already?

**Comment by twinssbc** [comment]
@abouttimeruss It's working for me. May I know how do you set your viewTitle when swiping to the previous/next view? I guess it's likely you are setting the viewTitle on a different "scope".

**Comment by abouttimeruss** [comment]
What you said lead me to the problem. Thanks!
