### ISSUE TITLE
Firebase integration example - Ionic 3

### ISSUE THREAD

**Issue by en-sevilla** [twinssbc/Ionic-Calendar#157]
Hi,

Please, has anyone a code example about how to integrate ionic-calendar 2 (ionic 3) with firebase? Which is the best approach?

 I think event list object should be syncrhonized via FirebaseListObservable<Events[]>, but I wonder is this is correct for a real-time app philosophy and if someone has an example, I am newby on Ionic 3.

Thanks in advance and congratulations to the author for this magnific code.

**Comment by twinssbc** [comment]
@en-sevilla Not sure if you have successfully integrated Firebase with the calendar.
This is for the Ionic1 version. I'm going to close this issue.
You could open a new one under https://github.com/twinssbc/Ionic2-Calendar, which works for Ionic 2 and 3.
