### ISSUE TITLE
can't change default of allDayLabel

### ISSUE THREAD

**Issue by JeongHwanMun** [twinssbc/Ionic-Calendar#158]
can't apply alldaylabel despite input 

![a](https://user-images.githubusercontent.com/6779228/30206829-50041ad2-94c8-11e7-9a27-82e4d89a1d6b.JPG)

![test](https://user-images.githubusercontent.com/6779228/30206799-2f3d8fb8-94c8-11e7-9153-6bbca1e8bba5.JPG)

**Comment by twinssbc** [comment]
@JeongHwanMun The allDayLabel only takes effect on the weekview and dayview. But I can release a quick fix for the month view.
