### ISSUE TITLE
Click previous or next months date in current view messes up calendar

### ISSUE THREAD

**Issue by abouttimeruss** [twinssbc/Ionic-Calendar#160]
In the Month view, if you click on a grey previous month day or next month day from the current calendar month view, it take you to that month, but the selected day starts going off. Then keep trying it for a previous month's day and it seems to get further out out of sync.

**Comment by twinssbc** [comment]
@abouttimeruss I can't reproduce this issue. Could you provide more details? Have you made any customization of the calendar? Do you meet the same issue in the Demo page?
http://twinssbc.github.io/Ionic-Calendar/demo/#/tab/home

**Comment by abouttimeruss** [comment]
Works. I needed range-changed="reloadSource(startTime, endTime)" declared in my calendar tag.
