### ISSUE TITLE
style is missed up when adding tags directly before calendar tag

### ISSUE THREAD

**Issue by alkahtani** [twinssbc/Ionic-Calendar#162]
I face an issue when adding any HTML tags  the calendar style get missing , the events shown behind the calendar , i tried also to extend nav-bar height the calendar is hiding behind the nav-bar 
![image](https://user-images.githubusercontent.com/13502824/31057653-05442bb6-a6ef-11e7-82a6-20a1e17afb57.png)

![image](https://user-images.githubusercontent.com/13502824/31057657-425a809a-a6ef-11e7-86e0-3ab300f8bf85.png)

any idea to be able to add HTML tags without getting the calendar style and appearance missed up, i am using ionic 1

**Comment by twinssbc** [comment]
@alkahtani This is because by default the margin-top of the event detail section is set to fixed 262px as below.
You could adjust the margin-top according to the element height added before the calendar.
```
.event-detail-container {
    margin-top: 262px;
}
```

**Comment by alkahtani** [comment]
@twinssbc  many thanks , this is fix the issue , it can be closed now . appreciate your help
