### ISSUE TITLE
calendar  is not loaded  in view 

### ISSUE THREAD

**Issue by vikas-kalyan** [twinssbc/Ionic-Calendar#164]
I have opened the modal in the another page  after that i open the calender in mypage the calendar month view in not loaded in the html

**Comment by twinssbc** [comment]
@vikas-kalyan Sorry, I don't quite understand how to reproduce your issue.
Are you saying you have a page containing the calendar, but it's not displayed by default.
You go to another page to open a modal.
Then go back to the previous page to somehow display the calendar, but it doesn't appear?
Is there any error printed out in the console?

**Comment by vikas-kalyan** [comment]
Yes your r right i also want to say that thing i mail you the screenshot
that appear it show one error but if i remive that it still nit shws the
calender

**Comment by vikas-kalyan** [comment]
Yes your r right i also want to say that thing i mail you the screenshot
that appear it show one error but if i remove that it still not show the
calender

**Comment by vikas-kalyan** [comment]
![whatsapp image 2017-10-28 at 11 28 59 am](https://user-images.githubusercontent.com/33048934/32131747-8fb74672-bbd3-11e7-9a59-921d80ac6b02.jpeg)

**Comment by vikas-kalyan** [comment]
![whatsapp image 2017-10-28 at 11 37 49 am](https://user-images.githubusercontent.com/33048934/32131798-d90da66c-bbd4-11e7-8838-2100033fc2e2.jpeg)

**Comment by vikas-kalyan** [comment]
Calender is open properly untill i m not open the modal in the another page but once i open modal and come back again open calender page  then i can't see the calender u can see in the image that i attach

**Comment by twinssbc** [comment]
@vikas-kalyan I can't reproduce this issue.
I have my home page having the calendar displayed.
In another page, it contains a "open modal" button.
When I click the "open modal" button, the modal dialog pops up. After I dismiss it and switch back to the home page, the calendar is still there.

**Comment by vikas-kalyan** [comment]
Please make  cache of states true

**Comment by twinssbc** [comment]
@vikas-kalyan Sorry, I have no idea about cache state? Is it related to this calendar component?
