### ISSUE TITLE
Calendar orientation Does not handled

### ISSUE THREAD

**Issue by manikandan07081995** [twinssbc/Ionic-Calendar#169]
I am using the calendar on iPad.When orientation occurs month view not appear.Sometimes one line of days only show.

**Comment by manikandan07081995** [comment]
![screen shot 2018-03-12 at 4 17 26 pm](https://user-images.githubusercontent.com/34768728/37279466-e752f14a-2610-11e8-80a6-810bce442a5a.png)

**Comment by twinssbc** [comment]
@manikandan07081995 I'm going to this issue. Don't create the same issue and comment the same questions at multiple places.

**Comment by manikandan07081995** [comment]
Okay, @twinssbc  I am just visible to you, not an intention.
