### ISSUE TITLE
How to change the viewTitle format for day

### ISSUE THREAD

**Issue by Raagu1993** [twinssbc/Ionic-Calendar#176]
How to change the viewTitle format for day?

**Comment by twinssbc** [comment]
@Raagu1993 You could use formatDayTitle option.

**Comment by Raagu1993** [comment]
Thanks, How to use formatDayTitle option in project? where to specify?
I have to display week name like "November 17, 2018 Monday".

Please find the below screen grab

![image](https://user-images.githubusercontent.com/20613013/48659458-a381ca00-ea77-11e8-92c7-841857f091d7.png)

**Comment by twinssbc** [comment]
@Raagu1993 You could use it as below in your HTML file.
```
format-day-title="MMMM dd, yyyy EEEE"
```

**Comment by Raagu1993** [comment]
Thanks, it is working fine
