### ISSUE TITLE
Understanding your code better - List and Year views

### ISSUE THREAD

**Issue by antoine92190** [twinssbc/Ionic-Calendar#20]
Hello again!
I'm trying to customize your Week view, and create a List and Year views on top of your calendar.
I'd like to have a better understanding of your code in order to take a good advantage of it.

=> List view: I'm trying to get all events in a single page, and order those by days.

<img width="377" alt="list" src="https://cloud.githubusercontent.com/assets/16256207/12873479/0fbe3426-cdbe-11e5-99e9-8424730deffa.png">

=> Week view: same as above, but using the sliding option to navigate between weeks.

<img width="377" alt="week" src="https://cloud.githubusercontent.com/assets/16256207/12873483/2203b160-cdbe-11e5-86a8-0a9b603c954f.png">

=> Year view: I want to display 12 months in a single page, and use the sliding option to navigate between years.

<img width="375" alt="year" src="https://cloud.githubusercontent.com/assets/16256207/12873485/280e84e0-cdbe-11e5-9a3d-6ce074c49df6.png">

It would help me so much to have your input about that and understand if and how those can be implemented using your calendar.

Again, thank you so much for everything!

**Comment by twinssbc** [comment]
@antoine92190 
Sure. I'd like to help you.
The view switching is controlled using **ng-switch-when** in the calendar.html, so you just need to add your own directive.
**CalendarController** is the main controller which contains some common logic, for example, slide change callback, place event logic.
You will see in some methods the main controller is calling the method having the underscore prefix, these underscore methods need to be implemented in the child controller. So it gives the child controller the chance to implement the customised logic. For example, in the **self.onEventSourceChanged** method, it calls **_onDataLoaded** method, and each view has its own way to load the data.
The main workflow is when the view is loaded, it calls self.render -> self.refreshView -> this._refreshView -> self.rangeChanged -> $scope.rangeChanged
When you slide the view, the workflow is scope.slideChanged -> self.move -> self.refreshView -> the same afterwards.

Let me know if you need more explanation. Thanks!

**Comment by antoine92190** [comment]
Thanks a lot for your explanation, I'll work on that and maybe ask you more later. Thanks again!
