### ISSUE TITLE
i18n - Translations

### ISSUE THREAD

**Issue by raphagodoi** [twinssbc/Ionic-Calendar#21]
we need to implement this...

**Comment by twinssbc** [comment]
@raphagodoi Could you give an example? Which part needs i18n?

**Comment by danny-36** [comment]
i18n for formatting Month or Day of the week in the correct language

**Comment by twinssbc** [comment]
I just include the angular locale script and the day header and view title can be translated correctly.
    <script src="http://code.angularjs.org/1.4.3/i18n/angular-locale_fr-fr.js"></script>

According to this article, the angular-translate can also help.
http://robferguson.org/2015/07/22/internationalisation-i18n-and-localisation-l10n-for-ionic-apps/

**Comment by danny-36** [comment]
interesting but the problem is the name of month displayed in calendar, for example "May, June, July" displayed in {{viewTitle}} on month view, how can I translate this in italian?

**Comment by twinssbc** [comment]
I just included below script, and the viewTitle is displayed as the below screenshot.
Does that meet your requirement?
    <script src="http://code.angularjs.org/1.4.3/i18n/angular-locale_it-it.js"></script>

![screen shot 2016-05-04 at 9 03 31 pm](https://cloud.githubusercontent.com/assets/3329841/15015077/5512c8b2-123c-11e6-8c59-56d40544ceba.png)

**Comment by danny-36** [comment]
Great! Thank you.
