### ISSUE TITLE
Week View Daylight Savings

### ISSUE THREAD

**Issue by ntuanb** [twinssbc/Ionic-Calendar#26]
Hi,

Currently I'm having a problem where the events displayed on the week the daylight savings occur, the time change hour is added onto events as soon as the daylight savings occur for all events.

This causes an slight hr problem for events in that week with + or - the daylight savings hour.

Would you know the best solution for this? 

I've looked into the code and fixed it using a few checks but its really dirty.

**Comment by twinssbc** [comment]
@ntuanb Do you store the time as UTC time? It shouldn't be impacted by DST.

**Comment by Manduro** [comment]
@twinssbc I'm having the same issue. The events in the calendar are suddenly positioned an hour later when I switch from the week of 21-27 march, to the week of 28 march-3 april. DST changes in the night between the 26th and 27th.

Time is stored as UTC time.

**Comment by Manduro** [comment]
@twinssbc My mistake, it seems my issue is out of the scope of this plugin. I was generating recurring events in UTC time without accounting for the DST.

**Comment by twinssbc** [comment]
@Manduro Yeah, it requires extra logic. It's not just the recurring events, I guess the normal events created previously are also shifted in the calendar.

**Comment by twinssbc** [comment]
@Manduro I think you need to store both UTC time and creator's time zone.
