### ISSUE TITLE
Bootstrap dependency

### ISSUE THREAD

**Issue by Manduro** [twinssbc/Ionic-Calendar#3]
Could you please explain what the dependency on Bootstrap is needed for? It seems to me that most of the time when you're using Ionic, you wouldn't want to include Bootstrap as well.

Maybe we can remove this dependency?

**Comment by twinssbc** [comment]
Yes, since the original version depends on Bootstrap so I didn't take it out.
It should be able to use the Ionic css classes to achieve the same thing.
I will make it work.

**Comment by Manduro** [comment]
@twinssbc That would be nice!

**Comment by twinssbc** [comment]
@Manduro I have removed the Bootstrap dependency, feel free to test it. Thanks.

**Comment by Manduro** [comment]
@twinssbc Works great, thanks!
