### ISSUE TITLE
queryMode is undefined even after overwriting the default value to 'remote'

### ISSUE THREAD

**Issue by ravindranpandu** [twinssbc/Ionic-Calendar#32]
Hi, The queryMode did not work, i tried using query-mode='remote' attribute in the calendar directive, when i debug the self.queryMode it shows undefined always and hence fallbacks to local.

`<calendar query-mode="remote"></calendar>`

**Comment by twinssbc** [comment]
@ravindranpandu It's not set directly in the directive, you need to assign it to a scope variable and set it in the controller.

**Comment by ravindranpandu** [comment]
@twinssbc it works now thanks, i have a weird issue now, when the range is changed the range-changed="" event is fired but the values are not updated in the calendar. 

`$scope.$parent.$watch($attrs.eventSource, function (value) {
       self.onEventSourceChanged(value);
 });`

when i add debugger to the watch code, it only triggers for the first time, after range-change when i try to reassign the new values to the $scope.eventSource the $watch is not triggered hence the calendar is loaded with empty events, am i missing something?

For your reference i am attaching my code below

`<calendar ng-model="calendar.currentDate" 
                        calendar-mode="calendar.mode" event-source="calendar.eventSource"
                        query-mode="queryMode" range-changed="reloadSource(startTime, endTime)"
                        event-selected="onEventSelected(event)" 
                        title-changed="onViewTitleChanged(title)"
                        time-selected="onTimeSelected(selectedTime)" step="30">
</calendar>`

`.controller('CalendarCtrl', function($scope, $state, $stateParams, Events) {
  $scope.calendar = {};         
  $scope.queryMode = "remote";
  
  $scope.changeMode = function (mode) {
      $scope.calendar.mode = mode;
  };

  $scope.onViewTitleChanged = function (title) {
      $scope.viewTitle = title;
  };

  $scope.today = function () {
      $scope.calendar.currentDate = new Date();
  };

  $scope.isToday = function () {
      var today = new Date(),
          currentCalendarDate = new Date($scope.calendar.currentDate);

      today.setHours(0, 0, 0, 0);
      currentCalendarDate.setHours(0, 0, 0, 0);
      return today.getTime() === currentCalendarDate.getTime();
  };

  $scope.onTimeSelected = function (selectedTime) {
      console.log('Selected time: ' + selectedTime);
  };

  $scope.onEventSelected = function (event) {      
      $state.go('tab.event-detail',{eventId: event.id});
  };

  $scope.reloadSource = function (startTime, endTime) {            
      $scope.calendar.eventSource = Events.all(startTime, endTime);            
      $scope.startTime = startTime;
      $scope.endTime = endTime;
  };  

  $scope.refreshCalendar = function(){
    $scope.calendar.eventSource = Events.all($scope.startTime, $scope.endTime);
    $scope.$broadcast('scroll.refreshComplete');
  }
})`

**Comment by twinssbc** [comment]
@ravindranpandu Does Events.all() always return the same object reference?
As I mentioned in the README, if you only modify the element in the eventSource array, the controller won't get notified. You need to manually broadcast the 'eventSourceChanged' event.

```
Note In the current version, the calendar controller only watches for the eventSource reference as it's the least expensive. That means only you manually reassign the eventSource value, the controller get notified, and this is usually fit to the scenario when the range is changed, you load a new data set from the backend. In case you want to manually insert/remove/update the element in the eventSource array, you can call broadcast the 'eventSourceChanged' event to notify the controller manually.
```

**Comment by ravindranpandu** [comment]
@twinssbc it works!!, thank you so much, as you guessed i am modifying the element in the eventSource array thats why the calendar is not updated with new events. calling the eventSourceChanged broadcast solves my problem :)
