### ISSUE TITLE
Translate option.

### ISSUE THREAD

**Issue by Alfonsibo** [twinssbc/Ionic-Calendar#34]
Hi, how can i translate the title of days and month in the calendar-mode month from English to another languages?. I am trying to translate in the fullcalendar lib but can't do this right. Can someone help me with a simple example?

Thank you!

**Comment by twinssbc** [comment]
@Alfonsibo I don't quite get which part of the title do you need to translate.
In the month view, it has below three options can control the text displayed in the month view
1. formatMonthTitle: control the title of that view, the default value is 'MMMM yyyy'
2. formatDay: control the text displayed for each day, the default value is 'dd'
3. formatDayHeader: control the text displayed in the header of the date table, the default value is 'EEE'

So you can change the format of month title as below:
```
            <calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource"
                      range-changed="reloadSource(startTime, endTime)"
                      event-selected="onEventSelected(event)" title-changed="onViewTitleChanged(title)"
                      time-selected="onTimeSelected(selectedTime)" formatMonthTitle='MMMM yyyy'></calendar>
```

**Comment by Alfonsibo** [comment]
I fixed my problem. Just want translate the text in viewTitle from April to Abril in the month view. I did it changing the value of $locale.DATETIME_FORMATS.MONTH and SHORTDAY for my local vars values. It's working fine for me.

`switch(idioma) {
      case 'es_ES':
        $locale.DATETIME_FORMATS.MONTH=trads.es_ES.MONTH;
        $locale.DATETIME_FORMATS.SHORTDAY=trads.es_ES.SHORTDAY;
      break;
      case 'en_EN':
        $locale.DATETIME_FORMATS.MONTH=trads.en_GB.MONTH;
        $locale.DATETIME_FORMATS.SHORTDAY=trads.en_GB.SHORTDAY;
      break;
    }`

Thanks for the help!
