### ISSUE TITLE
Options usage

### ISSUE THREAD

**Issue by danny-36** [twinssbc/Ionic-Calendar#35]
How can I use options from my controller?

**Comment by twinssbc** [comment]
@danny-36 You can refer to the demo page.

**Comment by danny-36** [comment]
for example how can I set "allDayLabel" from my template?

**Comment by twinssbc** [comment]
@danny-36 You can set the "allDayLabel" like below.

```
            <calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource"
                      range-changed="reloadSource(startTime, endTime)"
                      event-selected="onEventSelected(event)" title-changed="onViewTitleChanged(title)"
                      time-selected="onTimeSelected(selectedTime)" all-day-label="allDay"></calendar>
```

**Comment by danny-36** [comment]
doesn' t work. Can I set from my controller?

**Comment by twinssbc** [comment]
No, you can't, the option needs to be declared in the html.

**Comment by danny-36** [comment]
this is my template.
 <calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource"
              range-changed="reloadSource(startTime, endTime)"
              event-selected="onEventSelected(event)"
              title-changed="onViewTitleChanged(title)"
              time-selected="onTimeSelected(selectedTime)"
              all-day-label="Tutto il giorno"
              step="30"></calendar>

If I click on a all day event the label show is "all day" not "Tutto il giorno"

**Comment by twinssbc** [comment]
Ah, ok, the all-day-label option only applies to week view and day view right now. I will make it work for month view.

**Comment by danny-36** [comment]
![screenshot 11](https://cloud.githubusercontent.com/assets/18171609/14985649/af00006e-1148-11e6-9940-ce5b6446b463.jpg)

**Comment by twinssbc** [comment]
You need to adjust the width of the first column to fit your text. For example,

```
.calendar-hour-column, .weekview-allday-label, .dayview-allday-label {
	width: 100px;
}

.weekview-allday-content-wrapper, .dayview-allday-content-wrapper {
	margin-left: 100px;
}
```

**Comment by danny-36** [comment]
It seems more a problem of line-height

**Comment by twinssbc** [comment]
Yes, you can also adjust line-height if you want to wrap the text into multiple lines.

**Comment by danny-36** [comment]
I added this:
```
.calendar-hour-column, .weekview-allday-label, .dayview-allday-label {
  line-height: normal;
}
```
and works! thanks.
