### ISSUE TITLE
startingDayWeek not working

### ISSUE THREAD

**Issue by GeekMediaDK** [twinssbc/Ionic-Calendar#40]
When im using the startingDayWeek to set monday to be the first day of the week (`starting-day-week="1"`) it breaks the code. When swiping the week view it changes month at the same time, and it sets starting day to be wednesday when using the value 1.

Is this an issue or have i just misunderstood something about the option?

**Comment by twinssbc** [comment]
@GeekMediaDK It's a bug. I have fixed in version 0.2.4. Thanks!

**Comment by GeekMediaDK** [comment]
You'r welcome @twinssbc 

Hope you also can you my suggestion for the higlightclass function

**Comment by twinssbc** [comment]
@GeekMediaDK I have merged your PR and released in version 0.2.5. Thanks!

**Comment by veljkocasa** [comment]
I just installed version 0.3.3 and **startingDayWeek** not work...

**Comment by veljkocasa** [comment]
@twinssbc  can you check or hint ?

**Comment by twinssbc** [comment]
@veljkocasa startingDayWeek option is used like below. Could you have a try?

```
starting-day-week="1"
```

**Comment by veljkocasa** [comment]
tnx @twinssbc  on quick response!

I was using it like you say, but when I added  **starting-day-month="1"** it started to work perfectly...
So I guess it have to be paired...

solution looks like
`starting-day-week="1"  starting-day-month="1"`

tnx again
