### ISSUE TITLE
how to create event using only start date.

### ISSUE THREAD

**Issue by chandan4871** [twinssbc/Ionic-Calendar#42]
please any one help me to create the event having same start date and end date.
actually i have to create event only in a particular date and that will end in also that day, But when i provide same date in both start date and in end date the event is not binding to calendar.please help me urgent

**Comment by twinssbc** [comment]
@chandan4871 You need to put the end date to one day after start date

**Comment by chandan4871** [comment]
thanks a lot it works perfectly.Great work man
