### ISSUE TITLE
[request] Ionic2 Support

### ISSUE THREAD

**Issue by candelibas** [twinssbc/Ionic-Calendar#44]
Is there any hacky way to use this directive on Ionic 2 ?

**Comment by twinssbc** [comment]
@candelibas I haven' t tried it in Ionic 2, will look at it.

**Comment by candelibas** [comment]
@twinssbc would be great!

**Comment by twinssbc** [comment]
@candelibas I have ported the calendar to Ionic2. It's still at the very early stage, so may contain some bug.
Feel free to give it a try.
https://github.com/twinssbc/Ionic2-Calendar
