### ISSUE TITLE
showEventDetail does not appear to be working

### ISSUE THREAD

**Issue by zeiphon** [twinssbc/Ionic-Calendar#48]
Hi,

Attempting to set the option attribute like so: `show-event-detail="false"` does not appear to be taking effect, unless I'm missing something with the setting of this attribute.
This seems to be because at line 29 in calendar-tpls.js in your attribute option loop:
```javascript
self[key] = angular.isDefined($attrs[key]) ? (index < 10 ? $interpolate($attrs[key])($scope.$parent) : $scope.$parent.$eval($attrs[key])) : calendarConfig[key];
```

$interpolate will return a string value, and so self['showEventDetail'] is set to the string "false", a truthy value.

**Comment by twinssbc** [comment]
@zeiphon It's a bug and I have fixed in version 0.2.6. Thanks for reporting!

**Comment by zeiphon** [comment]
Thanks, that was quick!

Out of curiosity, why are you switching between `$interpolate` and `$scope.$parent.$eval` for various options?

**Comment by twinssbc** [comment]
@zeiphon I want to make some options like formatDay, allDayLabel can be declared directly in the HTML, as they normally don't change, while other options like queryMode, eventSource can be altered in the controller method.
