### ISSUE TITLE
Feature: clicking empty spot to create new event

### ISSUE THREAD

**Issue by Manduro** [twinssbc/Ionic-Calendar#5]
A common UX practice for calendars is to create a new event when clicking an empty spot in the week or day view.

The way I could see this implemented is to add an option called something like `timeslotSelected: function(startTime)`. When a user clicks (or long-presses on touch) an empty spot in the week or day view this function is called and is passed the time of the spot where was clicked.

This would be a pretty cool addition to this plugin!

**Comment by twinssbc** [comment]
@Manduro it's a good idea, I will add this feature.

**Comment by Manduro** [comment]
@twinssbc Or maybe I should just add a click handler to the template like you mentioned here: https://github.com/twinssbc/AngularJS-ResponsiveCalendar/issues/12

**Comment by twinssbc** [comment]
@Manduro I have added the timeSelected event to week and day view, feel free to have a test.

**Comment by Manduro** [comment]
@twinssbc Great, thanks! Seems to work fine.

**Comment by Manduro** [comment]
@twinssbc There is a bug in this functionality which I'm unable to trace. You can notice it in your demo as well: http://twinssbc.github.io/Ionic-Calendar/demo/#/tab/home

Open the week tab and click some empty spots in the current week. Watch the console logging of the time you clicked and you can see that they don't make sense. When you switch to the next or previous week it all works as expected, but when switching back to the current week it is still bugged.

Could you maybe have a look at this?

**Comment by twinssbc** [comment]
@Manduro Thanks for pointing it out. I have submitted the fix in version 0.1.4. Feel free to have a test. Thanks.

**Comment by Manduro** [comment]
Works!
