### ISSUE TITLE
Calendar doesn't work inside a ng-show container

### ISSUE THREAD

**Issue by dunice** [twinssbc/Ionic-Calendar#54]
Hi fellows,

Unfortunately the component doesn't work if is wrapped by a container with `ng-show` directive. But if I remove the directive it works fine.

**Comment by twinssbc** [comment]
@dunice What do you mean it doesn't work? Are you referring to the rendering or behaviour?
Could you provide the snippet how you use the calendar directive in the view?

**Comment by dunice** [comment]
@twinssbc Yes, I am referring about the rendering. If I remove the `ng-show` it renders ok. Check it out:

```javascript
<div ng-show="flight.clicked">
<calendar ng-model="calendar.currentDate" calendar-mode="calendar.mode" event-source="calendar.eventSource" range-changed="reloadSource(startTime, endTime)" event-selected="onEventSelected(event)" title-changed="onViewTitleChanged(title)" time-selected="onTimeSelected(selectedTime)" query-mode="remote"></calendar>
</div>
```

**Comment by dunice** [comment]
Fixed using `ng-if` instead.
