### ISSUE TITLE
Can we add indicators of the events in calendar..so that all the events will be indicated, if so.. can you please explain how to implement

### ISSUE THREAD

**Issue by abhinay100** [twinssbc/Ionic-Calendar#57]

**Comment by twinssbc** [comment]
@abhinay100 Could you give an example? What kind of indicator do you want?

**Comment by abhinay100** [comment]
![image](https://cloud.githubusercontent.com/assets/11390158/16406039/6a89ffea-3d29-11e6-8a00-7278bf6b933d.png)

this is the project where i have used the calendar.Im getting the events based on dates..just like todays indicator which is in green i need a indicator which indicates for all the events is this possible..can you please provide a code snippet

**Comment by abhinay100** [comment]
ex:if the events are in 15th and 20th they should be indicated with blue color

**Comment by twinssbc** [comment]
@abhinay100 Did you check my demo page?
http://twinssbc.github.io/Ionic-Calendar/demo/#/tab/home
If you click the LoadEvents, it will generate some random events on the calendar.
You can refer to the code in my demo page to implement your logic.

**Comment by abhinay100** [comment]
yes i checked.. i dint find any loadevents() in the js file

**Comment by abhinay100** [comment]
it will be helpful if u send the logic used in loadevents() 

Thanks

**Comment by twinssbc** [comment]
@abhinay100 Check https://github.com/twinssbc/Ionic-Calendar/blob/master/demo/calendarDemoCtrl.js
Search for the loadEvents function.

**Comment by abhinay100** [comment]
Thanks.. got it
