### ISSUE TITLE
Can I use it with Ionic 2 framework?

### ISSUE THREAD

**Issue by melsayed008** [twinssbc/Ionic-Calendar#58]
Hi, I'am using ionic 2 latest version and I am not sure if I can use the calendar with ionic2 framework? if not, is there another plugin can be used? Also should I be aware of anything to get it to work with ionic2 framework?
Thank you

**Comment by twinssbc** [comment]
@melsayed008 It's not working with Ionic2 framework. There are similar questions raised by other user. I'm starting converting it to Ionic2 compatible version.

**Comment by peterarends** [comment]
@twinssbc that would be awesome!

**Comment by twinssbc** [comment]
@peterarends I have ported the calendar to Ionic2. It's still at the very early stage, so may contain some bug.
Feel free to give it a try.
https://github.com/twinssbc/Ionic2-Calendar

**Comment by peterarends** [comment]
Thank you so much @twinssbc! Will give it a try now!
