### ISSUE TITLE
Pre-render events in previous/next view

### ISSUE THREAD

**Issue by Manduro** [twinssbc/Ionic-Calendar#6]
Sorry to bother you again ;).

When switching to the previous or next view, it takes a short time to render the events. I'm thinking the user experience would be greatly improved if the events are already there when switching views. Do you agree?

As the slides are already in the DOM it could be easy to build. I've already looked into it a little bit, and it seems that you're filtering the eventSource for events that are in the current view. I've tried expanding this range to include the previous and next view but I can't get it to work.

Can you help me with this?

And let's be clear on this: I have no problem contributing, so maybe you only have to point me in the right direction and I can build it. I'm the one needing it after all :).

**Comment by twinssbc** [comment]
@Manduro I'm always happy to help you.
First thing you probably already noted is that the previous and next views don't have the event bound in the templates. So you have to enable that.
Second, as you discovered, in _onDataLoaded function, I compare the event time with some start and end time to only include the events in the range, so you need to change the start and end time to include more events.

Apart from the user experience aspect, you probably also need to consider the performance and transmitted data size.
I've already added some timeout logic in the code to delay as much calculation logic as possible to make the animation when switch between views be smooth. You probably can adjust the timeout time to see if the event load and rendering can be quicker.

Let's say even you want to prepare the event beforehand, how many days of events do you want to prepare? In a mobile device, I think it's not reasonable to load a lot of unnecessary data. But if you only load next day events, each time you switch to the next view, you still need to load the next next day events and there's chance that user already switches to the next next view, but the events on that day  hasn't been prepared.

**Comment by Manduro** [comment]
@twinssbc I had already changed the template to bind the data to the previous and next views. This actually *improved* the performance for me, I think because not the whole view has to be re-rendered when the slide changes as per `ng-if="$index===currentViewIndex"`, only the events inside it. The initial render might take longer though. Below is my current template for the week view (which is the only view I need at the moment).

I tried to change the start and endtime in `_onDataLoaded` but it didn't seem to work. I use the remote mode by the way, which might matter?

Performance could be an issue yes, but mostly for the month view I guess. I'd like to try if I can make it fast enough ;). The next next scenario you mention stands, but if a user wants to switch that fast I don't think he'll have to wait longer than he has to on every switch as it is now.

```html
<div class="weekview">
  <ion-slide-box class="weekview-slide" on-slide-changed="slideChanged($index)" does-continue="true" show-pager="false">
    <ion-slide ng-repeat="view in views track by $index">
      <table class="table table-bordered table-fixed weekview-header">
        <thead>
          <tr>
            <th class="calendar-hour-column"></th>
            <th class="weekview-header" ng-repeat="dt in view.dates">{{::dt.date | amDateFormat:'D dd'}}</span></th>
          </tr>
        </thead>
      </table>
      <ion-content class="weekview-normal-event-container" delegate-handle="calendar" has-bouncing="false">
        <table class="table table-bordered table-fixed weekview-normal-event-table">
          <tbody>
            <tr ng-repeat="row in view.rows track by $index">
              <td class="calendar-hour-column text-center">
                {{ ::($index === 0 ? 24 : $index) }}
              </td>
              <td ng-repeat="tm in row track by tm.time" class="calendar-cell">
                <div ng-class="{'calendar-event-wrap': tm.events}" ng-if="tm.events">
                  <div ng-repeat="displayEvent in tm.events" class="calendar-event"
                       ng-click="eventSelected({event:displayEvent.event})"
                       ng-style="{left: 100/displayEvent.overlapNumber*displayEvent.position+'%', width: 100/displayEvent.overlapNumber+'%', height: 33*(displayEvent.endIndex-displayEvent.startIndex)+'px'}">
                    <div class="calendar-event-inner" ng-style="{backgroundColor: displayEvent.event.backgroundColor}">{{::displayEvent.event.title}}</div>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </ion-content>
    </ion-slide>
  </ion-slide-box>
</div>
```

**Comment by twinssbc** [comment]
@Manduro Since I can't see your complete code, I can just provide some tips.
1. You need to make sure the data sent from the backend also includes multiple weeks data
2. Check normalEventInRange or allDayEventInRange are true in _onDataLoaded method, which means there are some events left after filtering.
3. The events are placed using position:absolute, not sure if this could cause the events not visible in the current view. Try putting some text in the cell having events to see if it is visible.

**Comment by Manduro** [comment]
@twinssbc I've put some more time into it and have managed to get it working. I only changed the _onDataLoaded method of the week view (aside from the custom template I posted before). You can look into it here: https://github.com/Manduro/Ionic-Calendar/commit/d5a498c91b641915e4dab155e7f2fa44c9aa71af#diff-eb42bd619c59b52cc76cf6a85e5528a8

It might not be a really clean solution, but it works and is fast enough for me. Could be nice to implement this as an option?

**Comment by Manduro** [comment]
@twinssbc It seems that you aren't interested in adding this to the plugin? That's ok, I'll just keep it in my fork then.
