### ISSUE TITLE
allow easier template customization

### ISSUE THREAD

**Issue by bianchimro** [twinssbc/Ionic-Calendar#60]
Hi @twinssbc and thanks for this great widget.

I'm using it in a project and obviously ran into the need of customizing the templates.
I think this is quite common, for a various set of use cases:

* showing the calendar with other complex widgets on a view
* adding custom data to events

Some options could be provided in order to load different templates without modifying/forking the source code.

Another possible enhancement would be having smaller/specialized templates that could allow customization without touching the main templates, that tends to be quite complex due to the richness of the widget. For example, there could be a separate template for the `events-container` div, or even for the single cell of a month view. (Just an idea, probably not a good one ;) )

Best regards
Mauro

**Comment by twinssbc** [comment]
@bianchimro Yes, there are more and more users asking for similar customisation capability.
I will work on that.

**Comment by bianchimro** [comment]
@twinssbc perfect, I will stay tuned for updates. 
And thanks for your quick response, good work on the project!

**Comment by twinssbc** [comment]
@bianchimro I have added view customisation support in version 0.3.0.
It now supports customisation the event cell in month/week/day view and the event detail section in month view.

**Comment by bianchimro** [comment]
great @twinssbc, thanks a lot for your work, I'm going to test it this week in a couple of use cases and let you know how it goes. 
I'm going to close this issue now, thanks again!

regards 
Mauro
