### ISSUE TITLE
Prevent onTimeSelected when selecting an event in weekView or dayView

### ISSUE THREAD

**Issue by lucasdoamaral** [twinssbc/Ionic-Calendar#61]
When you are using the week or day view, if you click in an event the events onEventSelected and onTimeSelected are triggered. What can I do to prevent the onTimeSelected to be fired in this case?

**Comment by twinssbc** [comment]
@lucasdoamaral If you don't specify time-selected="onTimeSelected(selectedTime)" in the html, nothing will be triggered.

**Comment by lucasdoamaral** [comment]
I already specified a function to trigger in both onTimeSelected and onEventSelected, but in the week or day views, I would like to fire just the event onEventSelected, and prevent the onTimeSelected to be triggered. Got it?

**Comment by twinssbc** [comment]
@lucasdoamaral onTimeSelected function can't be disabled. But in your function you can simply check the current calendar mode and exit.

**Comment by lucasdoamaral** [comment]
In week view, for example:

Click **on a time** that doesn't have an event, trigger **onTimeSelected(timeSelected)**.
Click **on an event** trigger **onTimeSelected (timeSelected)** and **onEventSelected(eventSelected)**.

What I am trying to achieve is, when the user clicks on a event, I want to trigger the onEventSelected(eventSelected) (this is ok) but I want to event onTimeSelected(onTimeSelected) NOT to be triggered.

I am handling this by a controll variable, set when the onEventSelected is triggered and reset by a timeout function, but I'm sure this is just a workaround and could be solved in a better way.

**Comment by twinssbc** [comment]
@lucasdoamaral I got your requirement now.
I can think out two solutions:
1. Add a new flag, such as triggerTimeSelectedWhenNoEvent, and in the calendar code, it will check this flag to no trigger onTimeSelected function. But introducing a new flag requires more code.
2. Pass the associated events as the second parameter to the onTimeSelected function. And let user decide what to do. This requires less code change, and gives user more control.

So if no objection, I will implement the second approach.

**Comment by lucasdoamaral** [comment]
The two approachs resolve this requirement, althought I think the second approach is more elegant, cause when using the calendar, it will not be necessary to use a lot of attributes. IMO you should implement this using the second approach. I'm looking forward for this, so I could remove the $timeout function of my code. Thank you so much for your time!!!

**Comment by twinssbc** [comment]
@lucasdoamaral I have published the change in version 0.2.8.
The README file contains the explanation of the onTimeSelected method. 
Could you have a try? Thanks.

**Comment by lucasdoamaral** [comment]
Sure! I'll give it a try and let you know.

**Comment by lucasdoamaral** [comment]
It worked! Exactly what I needed! Thank you so much! :clap:

In the explanation about onTimeSelected you said:
> **timeSelected**
> The callback function triggered when a date is selected **in the monthview**. If there's no event at the selected time, the events parameter will be either undefined or empty array
I think you should remove "in the monthview", since the behaviour is the same in both day, week and month view.

I also suggest you to include an explanation that onEventSelected will be triggered even when onTimeSelected is defined, just to avoid any confusion.

Thank you again for your help and congratulation for your awesome plugin!

**Comment by twinssbc** [comment]
@lucasdoamaral Thanks for the suggestion, I will change the explanation.
