### ISSUE TITLE
does this works with ionic 2 too

### ISSUE THREAD

**Issue by abdulwahabkhan1** [twinssbc/Ionic-Calendar#62]
Hi i have question not an issue does this works with ionic 2 too

**Comment by twinssbc** [comment]
@abdulwahabkhan1 This control doesn't work with Ionic2 right now. I'm writing a new version for Ionic2.

**Comment by abdulwahabkhan1** [comment]
Thanks @twinssbc

**Comment by twinssbc** [comment]
@abdulwahabkhan1  I have ported the calendar to Ionic2. It's still at the very early stage, so may contain some bug.
Feel free to give it a try.
https://github.com/twinssbc/Ionic2-Calendar
