### ISSUE TITLE
issue with the month and an unexpected error

### ISSUE THREAD

**Issue by niksell** [twinssbc/Ionic-Calendar#64]
![image](https://cloud.githubusercontent.com/assets/9380686/16986914/f1208cbc-4e91-11e6-8d8b-4852712d6f31.png)
My app layout is like this and i cant see the month how i will fix this ?
And also i am gettin the error in the down right corner of the screen any clue ? None of my events is allDay

**Comment by twinssbc** [comment]
@niksell 
As describes in the Ionic documentation, http://ionicframework.com/docs/api/directive/ionTabs/

> For iOS, tabs will appear at the bottom of the screen. For Android, tabs will be at the top of the screen, below the nav-bar. This follows each OS’s design specification, but can be configured with the $ionicConfigProvider.

Regarding the error you get, could you reference the non minified version, calendar-tpls.js?
Then you should be able to locate which exact line has error and do some debugging.
I suspect event.startTime is not a Date object, but a String, could you have a check if you passed in the correct data type?

**Comment by niksell** [comment]
@twinssbc
My end and start time are in string format because I am getting them from an api. 
So you say that the problem with the month  is the position of the tabs?

**Comment by twinssbc** [comment]
@niksell Sorry, I misunderstand your first question. I thought you were talking about the layout is different in IOS and Android.
I think you meant you can't see the month in the title bar? Probably it's also related to the different  button position in IOS and Android.
