### ISSUE TITLE
Syntax Issue?

### ISSUE THREAD

**Issue by malik022** [twinssbc/Ionic-Calendar#7]
https://docs.angularjs.org/error/$parse/syntax?p0=:&p1=not%20a%20primary%20expression&p2=1&p3=::view.dates%5B0%5D.label&p4=::view.dates%5B0%5D.label

Is the error i am getting?

`Syntax Error: Token ':' not a primary expression at column 1 of the expression [::view.dates[0].label] starting at [::view.dates[0].label].`

**Comment by twinssbc** [comment]
@malik022 :: is the new syntax in Angular 1.3, it means one-time binding. It can improve the performance by reducing a lot of unnecessary watchers.
