### ISSUE TITLE
Every half hour in the day view

### ISSUE THREAD

**Issue by xiaolongtang** [twinssbc/Ionic-Calendar#77]
Hi there, this is framework is so awesome. I am wondering is that possible to show  every half hour in a row like "8:30AM,9:00AM,9:30AM" in the day view? If so, it will be so nice of you to point out where I should modify. Appreciate your help.

**Comment by twinssbc** [comment]
@xiaolongtang What do you mean show every half hour in a row?
Maybe you mean show every half hour in a column?
The **step** option already provides you the capability to display the event every half hour.

If you want to also display text like 8:30AM, 9:00AM in the first column, you can take a look at the day.html.
Below code snippet display the content in the first hour column. 

```
                       <td class="calendar-hour-column text-center">
                            {{::tm.time | date: formatHourColumn}}
                        </td>
```

**Comment by xiaolongtang** [comment]
@twinssbc right, it is every half hour in a column. Thank you so much.
