### ISSUE TITLE
Calendar event on-hold

### ISSUE THREAD

**Issue by NisanurBulut** [twinssbc/Ionic-Calendar#91]
hi how can ı add on-hold function to for each event because ı want to delete a event from my database when ı touch long .. thanks

**Comment by twinssbc** [comment]
@NisanurBulut You need to modify the source code to add the on-hold callback.
For example, in the weekview.html, you can add on-hold attribute the same as ng-click="eventSelected()" attribute.
You can follow the same way as eventSelected to expose the event to the client.

But one thing to note that in the current design of weekview and dayview.
The event width will become very small when there are many events happen at the same day.
In this case, you can't distinguish which event when holding on a date.
You may reconsider your interaction.

```
                                <div ng-class="{'calendar-event-wrap': tm.events}" ng-if="tm.events">
                                    <div ng-repeat="displayEvent in tm.events" class="calendar-event"
                                         ng-click="eventSelected({event:displayEvent.event})" on-hold="onTouchEvent({event:displayEvent.event})"
                                         ng-style="{top: (37*displayEvent.startOffset/hourParts)+'px',left: 100/displayEvent.overlapNumber*displayEvent.position+'%', width: 100/displayEvent.overlapNumber+'%', height: 37*(displayEvent.endIndex -displayEvent.startIndex - (displayEvent.endOffset + displayEvent.startOffset)/hourParts)+'px'}"
                                         ng-include="::normalEventTemplateUrl">
                                    </div>
                                </div>

```

**Comment by NisanurBulut** [comment]
hi yes ı did how to call ontouch evennt ? for example you call ebent selected function  event-selected="onEventSelected(event)" How must ı do it ? again thanks

**Comment by twinssbc** [comment]
@NisanurBulut You need to expose that method to the user. Similar to how eventSelected is implemented.

In the scope declaration of calendar directive:
```
eventSelected: '&'
```

**Comment by NisanurBulut** [comment]
sorry I am trying to modifying these operations.Should I modify calendar-tpls.js files ? thanks again

**Comment by twinssbc** [comment]
Great.
Btw, I saw your previous comment.
calendar-tpl.js is generated.
It's better to modify the src/rcalendar/calendar.js, then use grunt build-tpls to generate the tpl file.
