### ISSUE TITLE
Different color by event

### ISSUE THREAD

**Issue by ghadeerrahhal** [twinssbc/Ionic-Calendar#92]
Hey. Is it possible to change the color of the event based on an event property?

Thanks
~Ghadeer

**Comment by twinssbc** [comment]
@ghadeerrahhal It's possible.
You can pass in your own template which uses some event property.
You can get more detail from the View Customisation Options section in README.

**Comment by ghadeerrahhal** [comment]
Fantastic, thank you!

**Comment by gsaikrishna32** [comment]
when i am installing the plugin it is displaying errors like 'typings install'

**Comment by twinssbc** [comment]
@gsaikrishna32 Could you open a separate issue instead of commenting under existing issue?
You need to run below command to install typings.

```
npm install -g typings
```

**Comment by shalini-raghu** [comment]
hi how to change the background color of past days from today in calendar

**Comment by twinssbc** [comment]
@shalini-raghu Do you want to disable the past days? If so, you could use **isDateDisabled**  callback.
If you just want to change the background color without disabling the click event, you could use the **monthviewDisplayEventTemplateUrl** option. You could get more details in README.
