### ISSUE TITLE
The timezone changes when I go to the next month

### ISSUE THREAD

**Issue by GijsGoudzwaard** [twinssbc/Ionic-Calendar#93]
When I go to the next month it will go from
`Sat Oct 01 2016 00:00:00 GMT+0200 (CEST)`

to
`Tue Nov 01 2016 00:00:00 GMT+0100 (CET)`

This is what i'm doing:
`$scope.onViewTitleChanged = function(title) {  
        console.log(new Date(title));
    };`

It only happens when I go to the next months not the previous ones

**Comment by twinssbc** [comment]
@GijsGoudzwaard
I think this is expected because of DST?

```
> new Date(2016, 09, 1)
< Sat Oct 01 2016 00:00:00 GMT+0200 (CEST)
> new Date(2016, 10, 1)
< Tue Nov 01 2016 00:00:00 GMT+0100 (CET)
```

**Comment by GijsGoudzwaard** [comment]
You set me on the right track, it was because of DST.
I managed to fix my problem by using new Date() instead of moment js

**Comment by vaskolekoski** [comment]
I got the same problem, can you give me some guidelines how to solve DST?
