### ISSUE TITLE
change calendar title

### ISSUE THREAD

**Issue by NisanurBulut** [twinssbc/Ionic-Calendar#95]
hi, I change all view title with using tr.js angularjs source.But I cant change Week word. 

![ekran alintisi](https://cloud.githubusercontent.com/assets/9026717/19726110/e2bf4c92-9b91-11e6-93a2-3a4d6daf613c.PNG)

**Comment by twinssbc** [comment]
@NisanurBulut Actually calendar title is an option exposed to the user, you don't bother to change the source code.
When you declare the calendar directive in HTML, you just need to add the format-week-title option.
You can get more information from README.

```
<calendar ... format-week-title="MMMM yyyy, 'haha' w"></calendar>
```

**Comment by NisanurBulut** [comment]
thanks I finish your help Good Works ! :)
