### ISSUE TITLE
How can I add a delete event functionality ?

### ISSUE THREAD

**Issue by Debdazeworks** [twinssbc/Ionic-Calendar#98]
How to add a 'X' symbol and onclick event to delete a calendar event?

**Comment by twinssbc** [comment]
@Debdazeworks Have a look at View Customization Options section in README. The calendar exposes some options to use your own template.

**Comment by Debdazeworks** [comment]
I have changed https://github.com/twinssbc/Ionic-Calendar/blob/master/templates/rcalendar/displayEvent.html file, but no change is reflected. Am I doing right?

**Comment by twinssbc** [comment]
So you directly modify the source code, in this case, you need to run grunt build-tpls to generate the dist file.
Actually you dont need to modify source code, just provide an external template file and assign to weekviewNormalEventTemplateUrl.

**Comment by Debdazeworks** [comment]
I found "weekviewNormalEventTemplateUrl" in two places 
1. https://github.com/twinssbc/Ionic-Calendar/blob/master/dist/js/calendar-tpls.js 
2. https://github.com/twinssbc/Ionic-Calendar/blob/master/src/rcalendar/calendar.js

Where should I change ? I have downloaded the whole file in my local system and demo page is working. If I delete the templates\rcalendar\displayEvent.html in my file system, then also  its working fine. How ?

**Comment by twinssbc** [comment]
@Debdazeworks you don't need to modify the source code.
You just create your own template file, for example, myTemplate.html.
When you declare the calendar, pass your own template to weekview-normal-event-template-url

```
<calendar ... weekview-normal-event-template-url="weekviewNormalEventTemplateUrl"></calendar>
$scope.weekviewNormalEventTemplateUrl = 'myTemplate.html';
```

**Comment by Debdazeworks** [comment]
Thanks a lot man. It works.... (Y)
